#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=========================================="
echo "  Ecommerce Local Docker Quick Start"
echo "=========================================="
echo ""
echo "Using:"
echo "  Config: ${ROOT_DIR}/.env"
echo "  Frontend local env: ${ROOT_DIR}/frontend/.env.local"
echo "  Compose stack: ${ROOT_DIR}/docker-compose.yml"
echo ""
echo "Start the full local stack with:"
echo ""
echo "  cd ${ROOT_DIR}"
echo "  docker compose up --build"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo "  Backend:  http://localhost:8080/api/products"
echo "  RabbitMQ: http://localhost:15672"
echo ""
echo "Useful commands:"
echo "  docker compose up -d --build"
echo "  docker compose logs -f backend"
echo "  docker compose logs -f frontend"
echo "  docker compose down"
echo ""
echo "Notes:"
echo "  - Google OAuth needs localhost redirect URIs added in Google Cloud."
echo "  - MoMo IPN cannot reach localhost unless you expose the backend with a public tunnel."
